program: train.py
method: bayes
metric:
  name: val_auc
  goal: maximize
parameters:
  batch_size:
    # values: [16, 32]
    values: [16, 32, 64]
  epochs:
    value: 40
  # metadata_csv:
  #   values: ../data/processed/cbis_ddsm_metadata_full.csv
  base_learning_rate:
    value: 0.0002
  num_workers:
    value: 4
  lr_multiplier:
    distribution: uniform
    min: 0.95
    max: 1.10
    # min: 0.8
    # max: 1.2
  dropout:
    distribution: uniform
    min: 0.17
    max: 0.20
    # min: 0.15
    # max: 0.25
  l2_reg:
    distribution: uniform
    min: 0.00006
    max: 0.00012
    # min: 0.00001
    # max: 0.00010
  input_shape:
    value: [256, 256]
  alpha:
    distribution: uniform
    min: 1.6
    max: 2.0
    # values: [0.5, 1.0, 2.0]
  beta:
    distribution: uniform
    min: 0.8
    max: 1.4
    # values: [0.5, 1.0, 2.0]
  task:
    value: multitask

# config:
#   early_stop:
#     patience: 10
#     min_delta: 0.001
#     metric: val_auc
#     mode: max
