---
title: "Introduction"
---

## Why Is Early Detection of Breast Cancer Important?

- High Global Burden:
Breast cancer is the most commonly diagnosed cancer and the leading cause of cancer-related death among women worldwide. In 2020, it accounted for **2.3 million new cases** (1 in 4 cancer diagnoses) and **685,000 deaths** (1 in 6 cancer deaths) globally (GLOBOCAN 2020).[@arnold2022;@sedeta2023]

- Improved Survival:
Early detection increases five-year survival rates to over 90%, enabling less invasive treatments (e.g., breast-conserving surgery instead of mastectomy) and better quality of life.

- Lower Costs & Better Outcomes:
It reduces healthcare costs, minimizes treatment-related side effects, and supports psychological well-being.

- Policy Momentum: On 4 February 2025, the UK government launched a landmark AI-driven breast cancer screening trial involving nearly 700,000 women.[@gov.uk2025] This initiative, part of the NHS 10-Year Plan, aims to:
  - Enhance early detection with AI support
  - Alleviate radiologist workload
  - Reduce mortality and improve system efficiency