_wandb:
    value:
        cli_version: 0.19.11
        m:
            - "1": epoch/accuracy
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": epoch/epoch
              "6":
                - 3
              "7": []
            - "1": epoch/val_loss
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": epoch/loss
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": epoch/val_accuracy
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": epoch/learning_rate
              "5": 2
              "6":
                - 1
                - 3
              "7": []
        python_version: 3.11.8
        t:
            "1":
                - 1
                - 2
                - 3
                - 5
                - 53
                - 55
            "2":
                - 1
                - 2
                - 3
                - 5
                - 53
                - 55
            "3":
                - 2
                - 7
                - 16
                - 23
                - 38
                - 39
                - 55
            "4": 3.11.8
            "5": 0.19.11
            "8":
                - 1
                - 2
                - 5
            "12": 0.19.11
            "13": darwin-arm64
architecture:
    value: shallow_cnn
batch_size:
    value: 8
epochs:
    value: 20
learning_rate:
    value: 0.0001
optimizer:
    value: Adam
